### PR TITLE
Do not convert Rack::Response to Rack::Response

### PR DESCRIPTION
**Pull request by dmitry**
While using https://github.com/aserafin/grape_logging grape middleware after an upgrading grape from 0.11 to 0.12 I've been stuck with an issue (https://github.com/aserafin/grape_logging/issues/6):

```
NoMethodError (undefined method `downcase' for 2:Fixnum)
```

That's because `Middleware#response` tries to convert `Rack::Response` to `Rack::Response` and fails.

### CODE REVIEW

**Comment by dblock** [comment]
Ouch. Can you please add a line to the CHANGELOG? I will probably cut a dot release with this since it's a regression.

**Comment by dmitry** [comment]
@dblock Rebased with `CHANGELOG` file.

**Comment by dblock** [comment]
Merged.

**Comment by kushkella** [comment]
Just ran into this problem. Will really appreciate a new release! Thanks!

**Comment by AndyDangerous** [comment]
I was just having the same problem, and I wonder if this PR fully fixes it. After building the gem from the latest source, I still had the problem, but it goes away when using 0.11.0.

**Comment by johnsinco** [comment]
+1.  Still seeing this exact error message after building a 0.12.1 version from master.

**Comment by dmitry** [comment]
What about using `gem 'grape', github: 'intridea/grape'`?

**Comment by AndyDangerous** [comment]
@dmitry That ought to be the same code in master, right? In any case, the problem is still there.

**Comment by dmitry** [comment]
@AndyDangerous can you show the full stacktrace?

**Comment by AndyDangerous** [comment]
Here it is, @dmitry 
```
2015-07-08 14:42:34 +0000: Rack app error: #<NoMethodError: undefined method `downcase' for 2:Fixnum>
/usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/utils.rb:501:in `[]'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/response.rb:53:in `[]'                                                                                                                                                                                                              4 /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:654:in `call'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/middleware/error.rb:27:in `block in call!'                                                                                                                                                                         6 /usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/middleware/error.rb:26:in `catch'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/middleware/error.rb:26:in `call!'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/middleware/base.rb:18:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/endpoint.rb:196:in `call!'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/endpoint.rb:184:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
/usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/api.rb:114:in `call'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/api.rb:44:in `call!'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/grape-735034b2486e/lib/grape/api.rb:39:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'                                                                                                                                                     22 /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/config.rb:17:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.3/lib/puma/rack_patch.rb:13:in `call'                                                                                                                                                                                                        24 /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.3/lib/puma/configuration.rb:51:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
/usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
/usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by patfrat** [comment]
Got the same error today on one of my project using Grape 0.12.0 !

```
Unexpected error while processing request: undefined method `downcase' for 2:Fixnum
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/utils.rb:501:in `[]'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/response.rb:53:in `[]'
	/var/lib/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:650:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:27:in `block in call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `catch'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/base.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/endpoint.rb:196:in `call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/endpoint.rb:184:in `call'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/api.rb:98:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/api.rb:33:in `call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/api.rb:29:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/cascade.rb:33:in `block in call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `each'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `call'
	/var/lib/gems/2.1.0/gems/rack-contrib-1.3.0/lib/rack/contrib/post_body_content_type_parser.rb:36:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'
	/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `call'
	/var/lib/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'
```

**Comment by dmitry** [comment]
@patfrat you have to use grape from master, because this patch isn't released in a new gem yet.

**Comment by patfrat** [comment]
Grape 0.10.0 is working for me ... not 0.11.0 nor 0.12.0

**Comment by patfrat** [comment]
@dmitry i use grape from master in my project
I have tested also grape v0.12.1 and it's still on error

**Comment by dmitry** [comment]
It's another issue, and the issue is in rails 4.2.3: https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L654

**Comment by dmitry** [comment]
Is it happens while tests or in a development/production mode?

**Comment by AndyDangerous** [comment]
For us, it was in development.

**Comment by dmitry** [comment]
@AndyDangerous @patfrat I believe you have to move grape middleware upper than `ConnectionManagement` to resolve this issue. But for sure it's not related to this issue at all.

Basically you are experiencing an issue inside `ConnectionManagement` because it wants an array of response, but receives instance of a class `Rack::Response` instead.

**Comment by patfrat** [comment]
In development mode too
I have tested with downgrading active-support in version 4.2.1 and using grape 0.12.0
Still the same error !

'''
Unexpected error while processing request: undefined method `downcase' for 2:Fixnum
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/utils.rb:501:in `[]'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/response.rb:53:in `[]'
	/var/lib/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:650:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:27:in `block in call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `catch'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/middleware/base.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/endpoint.rb:196:in `call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/endpoint.rb:184:in `call'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
	/var/lib/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/api.rb:98:in `call'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/api.rb:33:in `call!'
	/var/lib/gems/2.1.0/gems/grape-0.12.0/lib/grape/api.rb:29:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/cascade.rb:33:in `block in call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `each'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `call'
	/var/lib/gems/2.1.0/gems/rack-contrib-1.3.0/lib/rack/contrib/post_body_content_type_parser.rb:36:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'
	/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `call'
	/var/lib/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'
'''

**Comment by dmitry** [comment]
How do you mounting grape API?

**Comment by patfrat** [comment]
I am using Rack::Cascade.new [Api, ApiDoc, statics]
My API use grape-activerecord v 0.0.8 and activerecord and activesupport 4.2.1

**Comment by dmitry** [comment]
@patfrat but where do you put this Rack::Cascade instance?

**Comment by dmitry** [comment]
I believe we have to stop chatting here about your issues, and you have to create a new issue... because it's unrelated to this this fix at all.

**Comment by patfrat** [comment]
ok @dmitry

**Comment by dmitry** [comment]
#1059
